apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: devfile-sample-ogcj
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/pmacik-testing/tkrw-pr714-0075-0015-tenant/tkrw-pr714-0075-0015-app/devfile-sample-ogcj@sha256:f51dd03a2bf3b4783df07aba64863ce64b70dc79ea6461f15628bac15790f148
        name: my-nodejs
        resources: {}
status: {}
