apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: devfile-sample-ogcj
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: devfile-sample-ogcj
    app.kubernetes.io/part-of: tkrw-pr714-0075-0015-app
  name: devfile-sample-ogcj
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: nodejs-app
      app.kubernetes.io/instance: devfile-sample-ogcj
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: nodejs-app
        app.kubernetes.io/instance: devfile-sample-ogcj
    spec:
      containers:
      - image: quay.io/pmacik-testing/tkrw-pr714-0075-0015-tenant/tkrw-pr714-0075-0015-app/devfile-sample-ogcj@sha256:f51dd03a2bf3b4783df07aba64863ce64b70dc79ea6461f15628bac15790f148
        name: my-nodejs
        ports:
        - containerPort: 3001
          name: http
          protocol: TCP
        resources:
          requests:
            cpu: 10m
            memory: 50Mi
status: {}
